version: 2.1
jobs:
  setup_node:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Tests
          command: |
            pnpm nx run-many --target=test
      - run:
          name: Prepare Build
          command: |
            pnpm nx run-many --target=build
  release:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Fix hosts unknown for Github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Prepare Release
          command: |
            pnpm nx run-many --target=release --parallel=false --verbose
      - run:
          name: Publish Release
          command: |
            pnpm nx run-many --target=release-publish

workflows:
  deploy:
    jobs:
      - setup_node
      - build:
          requires:
            - setup_node
      - release:
          requires:
            - build
